include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    #- '**.freezed.dart'
    - '**.g.dart'
  plugins:
    - custom_lint
linter:
  rules:
    avoid_print: false
    prefer_single_quotes: true
