name: vampulv
description: Help for particular variation of werewolf.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  darq: ^2.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  json_diff: ^0.2.1
  logging: ^1.2.0
  meta: ^1.9.1
  quiver: ^3.2.1
  riverpod_annotation: ^2.1.1
  shared_preferences: ^2.2.0
  stack_trace: ^1.11.0
  web_socket_channel: ^2.4.0
  xrandom: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.5
  json_serializable: ^6.6.2
  riverpod_generator: ^2.2.3
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/roles/
